version: '2'
services:
  demo:
    image: "divaethm/demo-microservice:{{ docker_image_tag }}"
    restart: always
    ports:
     - "8080:8080"
    volumes:
     - /srv/conf/app:/srv/conf
#networks:
#  default:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.23.126.0/25
