---

##- include: pre_config.yml

- hosts: demo
  vars:
     docker_image_tag: "{{ lookup('env','tag') }}"
     deployment_system: "{{ lookup('env','deployment_system') }}"
  roles:
    - config_deploy
    - docker_remove_containers
    - docker_login
    - docker_service
